"""
FastMCP Server for MCP Clinical Agent.

Exposes read-only database querying, schema introspection, and CSV export capabilities
as MCP tools. Implements connection pooling, query timeouts, and strict database privilege
isolation to help with secure model execution.
"""

import asyncio
import csv
import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import psycopg_pool
from mcp.server.fastmcp import FastMCP

from config import DEBUG_MODE

# Skip "Processing request of type ListToolsRequest" when using stdio
if not DEBUG_MODE:
    logging.getLogger("mcp").setLevel(logging.WARNING)
    logging.getLogger("mcp.server").setLevel(logging.WARNING)
    logging.getLogger("mcp.server.lowlevel.server").setLevel(logging.WARNING)



# Restricted connection credentials
DB_DSN = (
    "host=localhost "
    "dbname=clinical_db "
    "user=llm_user "
    "password=llm_pass"
)

# Hard limit for single query execution time to prevent database lockups
QUERY_TIMEOUT_SECONDS = 60
EXPORT_DIRECTORY = Path(__file__).with_name("exports")


# Connection pool singleton managed with double-checked locking for thread safety
pool: psycopg_pool.AsyncConnectionPool | None = None
pool_lock = asyncio.Lock()


async def get_pool() -> psycopg_pool.AsyncConnectionPool:
    """Lazily initialize and return the async PostgreSQL connection pool.

    Uses double-checked locking to prevent race conditions during concurrent startup.
    """
    global pool

    if pool is None:
        async with pool_lock:
            if pool is None:
                pool = psycopg_pool.AsyncConnectionPool(
                    conninfo=DB_DSN,
                    min_size=2,
                    max_size=20,
                    open=False,
                )
                await pool.open()

    return pool


async def fetch_query_results(
    sql_query: str,
) -> tuple[list[str], list[tuple[Any, ...]]]:
    """Execute a SQL query within a pooled connection and enforce statement timeouts.

    Args:
        sql_query: The SQL SELECT statement generated by the model.

    Returns:
        A tuple of (column_names, result_rows).
    """
    connection_pool = await get_pool()

    async with connection_pool.connection() as conn:
        async with conn.cursor() as cur:
            # pyrefly: ignore [no-matching-overload]
            await cur.execute(
                f"SET LOCAL statement_timeout = '{QUERY_TIMEOUT_SECONDS}s'"
            )

            # Execute dynamic model SQL under restricted 'llm_user' database permissions
            await cur.execute(sql_query)  # type: ignore[arg-type]

            if cur.description is None:
                return [], []

            columns = [
                description[0]
                for description in cur.description
            ]
            rows = await cur.fetchall()

            return columns, rows


@asynccontextmanager
async def app_lifespan(server: FastMCP):
    """FastMCP lifespan hook to drain the connection pool on server shutdown."""
    try:
        yield
    finally:
        global pool
        if pool is not None:
            await pool.close()
            pool = None


server = FastMCP(
    "mcp-clinical-agent",
    lifespan=app_lifespan,
)


@server.tool()
async def execute_readonly_query(sql_query: str) -> str:
    """
    Execute a read-only PostgreSQL query against the clinical warehouse.

    Use this tool when warehouse data is needed to answer a question. The
    database connection uses llm_user, which has SELECT-only permissions.
    """
    columns, rows = await fetch_query_results(sql_query)

    if not columns:
        return "Query completed successfully. No rows were returned."

    result = [
        dict(zip(columns, row))
        for row in rows
    ]

    return str(result)


@server.tool()
async def get_database_schema() -> str:
    """
    Return the current public database schema, including columns, data types,
    primary keys, and foreign-key relationships.

    Use this tool before writing SQL when the current schema is not already
    available in the conversation.
    """
    columns_query = """
        SELECT
            table_name,
            column_name,
            data_type,
            character_maximum_length,
            numeric_precision,
            numeric_scale,
            is_nullable
        FROM information_schema.columns
        WHERE table_schema = 'public'
        ORDER BY table_name, ordinal_position;
    """

    constraints_query = """
        SELECT
            relation.relname AS table_name,
            constraint_info.conname AS constraint_name,
            CASE constraint_info.contype
                WHEN 'p' THEN 'PRIMARY KEY'
                WHEN 'f' THEN 'FOREIGN KEY'
            END AS constraint_type,
            pg_get_constraintdef(constraint_info.oid) AS definition
        FROM pg_constraint AS constraint_info
        JOIN pg_class AS relation
            ON relation.oid = constraint_info.conrelid
        JOIN pg_namespace AS namespace
            ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname = 'public'
          AND constraint_info.contype IN ('p', 'f')
        ORDER BY relation.relname, constraint_type, constraint_name;
    """

    column_names, column_rows = await fetch_query_results(columns_query)
    _, constraint_rows = await fetch_query_results(constraints_query)

    if not column_rows:
        return "No accessible tables were found in the public schema."

    column_index = {
        name: index
        for index, name in enumerate(column_names)
    }

    lines = ["Current PostgreSQL schema:", ""]
    current_table = None

    for row in column_rows:
        table_name = row[column_index["table_name"]]
        column_name = row[column_index["column_name"]]
        data_type = row[column_index["data_type"]]
        max_length = row[column_index["character_maximum_length"]]
        precision = row[column_index["numeric_precision"]]
        scale = row[column_index["numeric_scale"]]
        is_nullable = row[column_index["is_nullable"]]

        if table_name != current_table:
            if current_table is not None:
                lines.append("")

            lines.append(f"Table: {table_name}")
            current_table = table_name

        type_description = data_type

        if max_length is not None:
            type_description += f"({max_length})"
        elif data_type == "numeric" and precision is not None:
            type_description += f"({precision}, {scale or 0})"

        nullable_text = "NULL" if is_nullable == "YES" else "NOT NULL"

        lines.append(
            f"  - {column_name}: {type_description}, {nullable_text}"
        )

    if constraint_rows:
        lines.extend(["", "Keys and relationships:"])

        for (
            table_name,
            constraint_name,
            constraint_type,
            definition,
        ) in constraint_rows:
            lines.append(
                f"  - {table_name}.{constraint_name}: "
                f"{constraint_type} {definition}"
            )

    return "\n".join(lines)


@server.tool()
async def export_query_to_csv(
    sql_query: str,
    file_name: str = "query_results.csv",
) -> str:
    """
    Execute a read-only PostgreSQL query and save its complete result as a CSV
    file in the local exports directory.

    Use this tool only when the user asks to save or export query results. The
    file_name may be provided with or without the .csv extension.
    """
    columns, rows = await fetch_query_results(sql_query)

    if not columns:
        raise ValueError(
            "The CSV export query did not return any columns."
        )

    # Security: Strip path components via Path.name to prevent directory traversal vulnerabilities
    safe_file_name = Path(file_name).name.strip()

    if not safe_file_name:
        safe_file_name = "query_results.csv"

    if not safe_file_name.lower().endswith(".csv"):
        safe_file_name += ".csv"

    EXPORT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    output_path = EXPORT_DIRECTORY / safe_file_name

    with output_path.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(columns)
        writer.writerows(rows)

    return (
        "CSV export created successfully.\n"
        f"File: {output_path.resolve()}\n"
        f"Rows exported: {len(rows)}"
    )


if __name__ == "__main__":
    server.run(transport="stdio")

